crawl:
	ocamlbuild -use-ocamlfind -tag thread crawl.byte && ./crawl.byte

delay:
	ocamlbuild -use-ocamlfind -tag thread delay.byte && ./delay.byte

server:
	ocamlbuild -use-ocamlfind -tag thread server.byte && ./server.byte

clean:
	ocamlbuild -clean
